### ISSUE TITLE
关于example用法的文档完善

### ISSUE THREAD

**Issue by horanf** [mybatis-mapper/mapper-docs#2]
mapper 4的用户可能很熟悉，但像我这样直接使用mybatis-mapper的可能找到相关文档会很费劲，建议更新相关文档，或者引用[mapper 4 doc](https://github.com/abel533/Mapper/wiki/6.example)

**Comment by abel533** [comment]
和mapper4也不一样，可以看看单测：https://github.com/mybatis-mapper/mapper/blob/master/mapper/src/test/java/io/mybatis/mapper/example/UserExampleMapperTest.java
