### ISSUE TITLE
或许可以添加一个CONTRIBUTING.md

### ISSUE THREAD

**Issue by horanf** [mybatis-mapper/mapper-docs#3]
许多人应该是不熟悉vuepress的，或许可以添加一个像[mybatis 3/contributing.md](https://github.com/mybatis/mybatis-3/blob/master/CONTRIBUTING.md)的文档，帮助想要更新文档的开发者

**Comment by abel533** [comment]
可以加，你有意向参与吗？

**Comment by horanf** [comment]
> 可以加，你有意向参与吗？

是的，我很乐意

**Comment by abel533** [comment]
vuepress文档：https://vuepress.vuejs.org/zh/
如果用QQ，可以加群：277256950
